server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: pass123
#mysql://root:LQUImPLzFYWUcROVSvlECAUozKsFFHZh@nozomi.proxy.rlwy.net:18956/railway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
          client:
            registration:
              google:
                client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
                client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
                scope:
                  - email
                  - profile
                  - openid
#                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#                client-name: Google
              github:
                client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
                client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                scope:
                  - read:user
                  - user:email


logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:7Zp0pT7q3Xv8xF2Y6QmKc9B4NwR1LhS8uE5jD2Vg0yHkA3tP9sC6rM8UqWbXzFJY}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_TOKEN_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}


app:
  cors:
    front-end-url: ${FRONT_END_URL:http://localhost:5173}
  auth:
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_REDIRECT:http://localhost:3000/oauth/success}
      failure-redirect: ${FRONT_END_FAILURE_REDIRECT:http://localhost:3000/oauth/failure}


